# config for the shallow water model
water_model_config:
  # basic initialization parameters for the model state:
  base_velocity: 10.0
  base_height: 90.0
  base_rain: 0.0

  ngrid: 250 # number grid cells
  num_sub_steps: 120

  time_step_size: 5.0
  grid_spacing: 500.0

  h_cloud: 90.005 # height threshold to trigger phi replacement/convection
  h_rain: 90.1 # height threshold to trigger rain
  phi_cloud: 899.9 # phi value to replace if h surpasses h_cloud
  gravitational_constant: 10.0
  r_gamma: 1.0 # rain influence coefficient on potential phi
  u_diff_coef: 20000.0  # diffusion coefficient for the velocity
  h_diff_coef: 20000.0 # diffusion coefficient for the height
  r_diff_coef: 200.0 # diffusion coefficient for the rain
  r_removal_rate: 0.008
  r_rate: 50.0
  filter_coeff: 0.1
  filter_correction_past: 0.53
  filter_correction_present: -0.47
  
  wind_perturbation_standard_deviation: 4
  wind_perturbation_noise_amplitude: 0.002

observation_generation_config:
  u_error_std: 0.001
  u_error_mean: 0.0
  h_error_std: 0.01
  h_error_mean: 0.0
  r_error_std: 1.5
  r_error_mean: -8.0

  radar_rain_threshold: 0.005 # threshold for rain to observed by radar
  radar_no_rain_observation_percentage: 0.1 # percentage of no rain locations radar observes
  cov_inflation: 1.0
  grid_point_influence: 4 # number surrounding grid points to be influenced from outgoing grid point

global_config:
  out_path: ./out/
  base_seed: 42 # enforces reproducibility of experiments, change for different new runs