[project]
name = "msw-da-ml"
version = "0.1.0"
description = "Reimplementation of the the Paper 'Training a convolutional neural network to conserve mass in data assimilation' and their associated code https://github.com/wavestoweather/MSW_DA_ML/tree/v2.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
