# config for the shallow water model
water_model_config:
  # basic initialization parameters for the model state:
  base_velocity: 10.0
  base_height: 90.0
  base_rain: 0.0

  ngrid: 250 # number grid cells
  num_sub_steps: 120

  time_step_size: 5.0
  grid_spacing: 500.0

  h_cloud: 90.005 # height threshold to trigger phi replacement/convection
  h_rain: 90.1 # height threshold to trigger rain
  phi_cloud: 899.9 # phi value to replace if h surpasses h_cloud
  gravitational_constant: 10.0
  r_gamma: 1.0 # rain influence coefficient on potential phi
  u_diff_coef: 20000.0  # diffusion coefficient for the velocity
  h_diff_coef: 20000.0 # diffusion coefficient for the height
  r_diff_coef: 200.0 # diffusion coefficient for the rain
  r_removal_rate: 0.008
  r_rate: 50.0
  filter_coeff: 0.1
  filter_correction_past: 0.53
  filter_correction_present: -0.47
  
  wind_perturbation_standard_deviation: 4
  wind_perturbation_noise_amplitude: 0.002

shared_obs_gen_assimilation_config:
  u_error_std: 0.001
  u_error_mean: 0.0
  h_error_std: 0.01
  h_error_mean: 0.0
  r_error_std: 1.5
  r_error_mean: -8.0

  radar_rain_threshold: 0.005 # threshold for rain to observed by radar
  radar_no_rain_observation_percentage: 0.1 # percentage of no rain locations radar observes
  cov_inflation: 1.0
  grid_point_influence: 4 # number surrounding grid points to be influenced from outgoing grid point

network_config:
  in_channels: 4
  hidden_channels: 32
  num_layers: 5
  kernel_size: 3

loss_config:
  variable_to_punish_idx: 1 # Variable for bias loss, Default: 1; Options: 0: velocity, 1: height, 2: rain
  bias_loss_weight: 1 # Weighting for bias loss

training_config:
  val_split_size: 0.2
  random_state_train_test_split: 42
  batch_size: 32
  learning_rate: 0.001
  epochs: 100
  mcdo_dropout: 0.1
  
inference_config:
  inference_seed: 43 # difference seed, to ensure different setting
  num_ensemble_members: 10

experiment_config:
  base_seed: 43
  num_seeds: 10
  num_inference_steps: 200
  num_ensemble_members: 10

conformal_prediction_config:
  calibration_split_ratio: 0.5 # percentage of samples/random seeds to be utilized in calibration
  calibration_split_seed: 42
  calibration_quantile: 0.9 # calibration quantile, theoretical guarantee
  rain_normalization_eps: 1.0 # epsilon to be added to rain during normalization

global_config:
  out_path: ./out/
  visualizations_out_filename: visualizations/
  generated_data_animations_out_filename: training_sequence_animations/
  training_sequences_out_filename: training_sequences/
  trained_nn_model_out_filename: trained_nn_models/
  normalization_out_filename: normalization_stats/
  evaluation_sequences_out_filename: evaluation_sequences/
  trained_quantile_nn_model_out_filename: trained_quantile_nn_models/
  quantile_normalization_out_filename: quantile_normalization_stats/
  quantile_evaluation_sequences_out_filename: cqr_evaluation_sequences/
  base_seed: 42 # enforces reproducibility of experiments, change for different new runs
